### ISSUE TITLE
Copy of http://www.xprinter.net/products_show.asp?lan=zh-en&skin=1&newsid=239753224

### ISSUE THREAD

**Issue by BetaUliansyah** [Zn4rK/xp58#1]
Does someone keep a copy of file at http://www.xprinter.net/products_show.asp?lan=zh-en&skin=1&newsid=239753224 ? The site is not accessible right now.

**Comment by Zn4rK** [comment]
The website is perfectly accessible, but the above link seems to be broken. I would start looking here:
http://poskeytech.com/html/Drivers/
