### ISSUE TITLE
Execution on Mac OS

### ISSUE THREAD

**Issue by hongvan0922** [Zn4rK/xp58#3]
Hi, I can't execute the install-mac file on Mac. The error shows:

cp: rastertoxp58: No such file or directory
mkdir: /usr/share/cups/model/xprinter: Operation not permitted
cp: directory /usr/share/cups/model/xprinter does not exist
/Users/macbook
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

Is there a way to create the xprinter folder? Please help.

**Comment by Zn4rK** [comment]
New stuff in MacOS prevents us to write to /usr. 
https://www.macworld.co.uk/how-to/mac/how-turn-off-mac-os-x-system-integrity-protection-rootless-3638975/

Or try to modify the script to use /usr/local...
