### ISSUE TITLE
Error rastertoxp58.c:17:16: error: redefinition of typedef ‘__sighandler_t’ with different type  typedef void (*__sighandler_t)();

### ISSUE THREAD

**Issue by mboy1011** [Zn4rK/xp58#4]
![image](https://user-images.githubusercontent.com/24217468/62134183-a0cbba00-b312-11e9-8ad7-d45ed8a8bbef.png)

Complete Error Code: 
gcc -Wl,-rpath,/usr/lib -Wall -fPIC -O3 -c rastertoxp58.c                                                                                      rastertoxp58.c:17:16: error: redefinition of typedef ‘__sighandler_t’ with different type                                                       typedef void (*__sighandler_t)();                                                                                                                             ^~~~~~~~~~~~~~                                                                                                                 In file included from rastertoxp58.c:8:                                                                                                        /usr/include/signal.h:72:16: note: previous declaration of ‘__sighandler_t’ was here                                                            typedef void (*__sighandler_t) (int);                                                                                                                         ^~~~~~~~~~~~~~                                                                                                                 rastertoxp58.c: In function ‘getOptionChoiceIndex’:                                                                                            rastertoxp58.c:110:2: warning: ‘ppdFindMarkedChoice’ is deprecated: Use cupsCopyDestInfo and friends instead. [-Wdeprecated-declarations]        choice = ppdFindMarkedChoice(ppd, name);                                                                                                       ^~~~~~                                                                                                                                       In file included from rastertoxp58.c:4:                                                                                                        /usr/include/cups/ppd.h:385:22: note: declared here                                                                                             extern ppd_choice_t *ppdFindMarkedChoice(ppd_file_t *ppd,                                                                                                           ^~~~~~~~~~~~~~~~~~~                                                                                                      rastertoxp58.c:114:3: warning: ‘ppdFindOption’ is deprecated: Use cupsCopyDestInfo and friends instead. [-Wdeprecated-declarations]               if ((option = ppdFindOption(ppd, name)) == NULL) return -1;                                                                                    ^~                                                                                                                                          In file included from rastertoxp58.c:4:                                                                                                        /usr/include/cups/ppd.h:388:22: note: declared here                                                                                             extern ppd_option_t *ppdFindOption(ppd_file_t *ppd, const char *keyword)                                                                                            ^~~~~~~~~~~~~                                                                                                            rastertoxp58.c:115:3: warning: ‘ppdFindChoice’ is deprecated: Use cupsCopyDestInfo and friends instead. [-Wdeprecated-declarations]               if ((choice = ppdFindChoice(option,option->defchoice)) == NULL) return -1;                                                                     ^~                                                                                                                                          In file included from rastertoxp58.c:4:                                                                                                        /usr/include/cups/ppd.h:383:22: note: declared here                                                                                             extern ppd_choice_t *ppdFindChoice(ppd_option_t *o, const char *option)                                                                                             ^~~~~~~~~~~~~                                                                                                            rastertoxp58.c: In function ‘initializeSettings’:                                                                                              rastertoxp58.c:129:2: warning: ‘ppdOpenFile’ is deprecated: Use cupsCopyDestInfo and friends instead. [-Wdeprecated-declarations]                ppd = ppdOpenFile(getenv("PPD"));                                                                                                              ^~~                                                                                                                                          In file included from rastertoxp58.c:4:                                                                                                        /usr/include/cups/ppd.h:397:20: note: declared here                                                                                             extern ppd_file_t *ppdOpenFile(const char *filename) _PPD_DEPRECATED;                                                                                             ^~~~~~~~~~~                                                                                                                rastertoxp58.c:131:2: warning: ‘ppdMarkDefaults’ is deprecated: Use cupsCopyDestInfo and friends instead. [-Wdeprecated-declarations]            ppdMarkDefaults(ppd);                                                                                                                          ^~~~~~~~~~~~~~~                                                                                                                              In file included from rastertoxp58.c:4:                                                                                                        /usr/include/cups/ppd.h:392:14: note: declared here                                                                                             extern void  ppdMarkDefaults(ppd_file_t *ppd) _PPD_DEPRECATED;                                                                                              ^~~~~~~~~~~~~~~                                                                                                                  rastertoxp58.c:136:3: warning: ‘cupsMarkOptions’ is deprecated: Use cupsCopyDestInfo and friends instead. [-Wdeprecated-declarations]             cupsMarkOptions(ppd, numOptions, options);                                                                                                     ^~~~~~~~~~~~~~~                                                                                                                             In file included from rastertoxp58.c:4:                                                                                                        /usr/include/cups/ppd.h:370:13: note: declared here                                                                                             extern int  cupsMarkOptions(ppd_file_t *ppd, int num_options, cups_option_t *options) _PPD_DEPRECATED;                                                     ^~~~~~~~~~~~~~~                                                                                                                   rastertoxp58.c:147:2: warning: ‘ppdClose’ is deprecated: Use cupsCopyDestInfo and friends instead. [-Wdeprecated-declarations]                   ppdClose(ppd);                                                                                                                                 ^~~~~~~~                                                                                                                                     In file included from rastertoxp58.c:4:                                                                                                        /usr/include/cups/ppd.h:372:14: note: declared here                                                                                             extern void  ppdClose(ppd_file_t *ppd) _PPD_DEPRECATED;                                                                                                     ^~~~~~~~                                                                                                                         rastertoxp58.c: At top level:                                                                                                                  rastertoxp58.c:89:16: warning: ‘rasterModeStartCommand’ is static but used in inline function ‘rasterheader’ which is not static                 outputCommand(rasterModeStartCommand);                                                                                                                       ^~~~~~~~~~~~~~~~~~~~~~                                                                                                         make: *** [Makefile:16: rastertoxp58.o] Error 1

**Comment by Zn4rK** [comment]
Please try https://github.com/klirichek/zj-58 instead.

**Comment by mboy1011** [comment]
Thanks, it works.
